version: '3.8'

services:
  backend:
    image: hsense/inventory-analyzer-backend:1.0.5
    container_name: inventory-analyzer-backend
    ports:
      - "5011:5011"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    platform: linux/amd64

  frontend:
    image: hsense/inventory-analyzer-frontend:1.0.9
    container_name: inventory-analyzer-frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5011
    depends_on:
      - backend
    restart: unless-stopped
    platform: linux/amd64